# Generated by Django 5.1.8 on 2025-08-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourismlocation",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tourism/locations/",
                verbose_name="Gambar Utama",
            ),
        ),
    ]
