# Generated by Django 5.1.8 on 2025-08-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0002_add_main_image_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourismcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tourism/categories/",
                verbose_name="Gambar Kategori",
            ),
        ),
        migrations.AddField(
            model_name="tourismcategory",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tourism/categories/videos/",
                verbose_name="Video Kategori",
            ),
        ),
    ]
