# Generated by Django 5.1.8 on 2025-08-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0003_tourismcategory_image_tourismcategory_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourismcategory",
            name="youtube_link",
            field=models.URLField(blank=True, null=True, verbose_name="Link YouTube"),
        ),
        migrations.AddField(
            model_name="tourismpackage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tourism/packages/",
                verbose_name="Gambar Paket",
            ),
        ),
        migrations.AddField(
            model_name="tourismpackage",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tourism/packages/videos/",
                verbose_name="Video Paket",
            ),
        ),
        migrations.AddField(
            model_name="tourismpackage",
            name="youtube_link",
            field=models.URLField(blank=True, null=True, verbose_name="Link YouTube"),
        ),
    ]
