# Generated by Django 5.1.8 on 2025-08-31 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0004_tourismcategory_youtube_link_tourismpackage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismpackage',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor WhatsApp'),
        ),
    ]
