# Generated by Django 5.1.8 on 2025-08-31 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tourism", "0005_auto_20250831_2306"),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismgallery',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tourism.tourismpackage', verbose_name='Paket Wisata'),
        ),
        migrations.AlterField(
            model_name='tourismgallery',
            name='tourism_location',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tourism.tourismlocation', verbose_name='Lokasi Wisata'),
        ),
    ]
