# Generated by Django 5.1.8 on 2025-08-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("references", "0003_alter_penduduk_options_penduduk_blood_type_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="karangtaruna",
            index=models.Index(
                fields=["jabatan"], name="organizatio_jabatan_8afa62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="karangtaruna",
            index=models.Index(fields=["status"], name="organizatio_status_ea6c3b_idx"),
        ),
        migrations.AddIndex(
            model_name="karangtaruna",
            index=models.Index(
                fields=["nomor_anggota"], name="organizatio_nomor_a_635b6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="karangtaruna",
            index=models.Index(
                fields=["is_pengurus_inti"], name="organizatio_is_peng_58c404_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="karangtaruna",
            index=models.Index(
                fields=["jabatan", "status"], name="organizatio_jabatan_2ca9aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="karangtaruna",
            index=models.Index(
                fields=["status", "is_pengurus_inti"],
                name="organizatio_status_365524_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="karangtaruna",
            index=models.Index(
                fields=["status", "tanggal_bergabung"],
                name="organizatio_status_37a934_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kepemudaan",
            index=models.Index(
                fields=["nama_organisasi"], name="organizatio_nama_or_f8d9e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kepemudaan",
            index=models.Index(
                fields=["jenis_organisasi"], name="organizatio_jenis_o_41e79f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kepemudaan",
            index=models.Index(fields=["status"], name="organizatio_status_ac6d66_idx"),
        ),
        migrations.AddIndex(
            model_name="kepemudaan",
            index=models.Index(
                fields=["jenis_organisasi", "status"],
                name="organizatio_jenis_o_d4c58c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kepemudaan",
            index=models.Index(
                fields=["status", "tanggal_terbentuk"],
                name="organizatio_status_ce3aed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lembagaadat",
            index=models.Index(
                fields=["nama_lembaga"], name="organizatio_nama_le_f6766a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lembagaadat",
            index=models.Index(
                fields=["jenis_lembaga"], name="organizatio_jenis_l_aa4945_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lembagaadat",
            index=models.Index(fields=["status"], name="organizatio_status_7cce18_idx"),
        ),
        migrations.AddIndex(
            model_name="lembagaadat",
            index=models.Index(
                fields=["jenis_lembaga", "status"],
                name="organizatio_jenis_l_488c4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lembagaadat",
            index=models.Index(
                fields=["status", "tanggal_terbentuk"],
                name="organizatio_status_5e66c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="penggerakpkk",
            index=models.Index(
                fields=["jabatan"], name="organizatio_jabatan_2a42f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="penggerakpkk",
            index=models.Index(fields=["status"], name="organizatio_status_dbb5fb_idx"),
        ),
        migrations.AddIndex(
            model_name="penggerakpkk",
            index=models.Index(
                fields=["nomor_anggota"], name="organizatio_nomor_a_c02f6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="penggerakpkk",
            index=models.Index(
                fields=["jabatan", "status"], name="organizatio_jabatan_4435e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="penggerakpkk",
            index=models.Index(
                fields=["status", "tanggal_bergabung"],
                name="organizatio_status_5d90dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="perangkatdesa",
            index=models.Index(
                fields=["jabatan"], name="organizatio_jabatan_e62492_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="perangkatdesa",
            index=models.Index(fields=["status"], name="organizatio_status_7630ec_idx"),
        ),
        migrations.AddIndex(
            model_name="perangkatdesa",
            index=models.Index(fields=["nip"], name="organizatio_nip_634908_idx"),
        ),
        migrations.AddIndex(
            model_name="perangkatdesa",
            index=models.Index(
                fields=["jabatan", "status"], name="organizatio_jabatan_672508_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="perangkatdesa",
            index=models.Index(
                fields=["status", "tanggal_mulai_tugas"],
                name="organizatio_status_dac3e4_idx",
            ),
        ),
    ]
