# Generated by Django 5.1.8 on 2025-08-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_karangtaruna_organizatio_jabatan_8afa62_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="penggerakpkk",
            name="deskripsi_tugas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="penggerakpkk",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="penggerakpkk",
            name="sk_pengangkatan",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="penggerakpkk",
            name="tanggal_mulai_tugas",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="penggerakpkk",
            name="tanggal_selesai_tugas",
            field=models.DateField(blank=True, null=True),
        ),
    ]
