# Generated by Django 5.1.8 on 2025-08-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organization",
            "0003_penggerakpkk_deskripsi_tugas_penggerakpkk_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="kepemudaan",
            name="media_sosial",
            field=models.CharField(
                blank=True,
                help_text="Media sosial organisasi (Instagram/Facebook)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="kepemudaan",
            name="visi_misi",
            field=models.TextField(blank=True, help_text="Visi dan misi organisasi"),
        ),
    ]
