# Generated by Django 5.2.4 on 2025-08-26 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="news",
            name="reading_time",
            field=models.PositiveIntegerField(
                default=0, help_text="Estimasi waktu baca dalam menit"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True, help_text="Tanggal untuk publikasi otomatis", null=True
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="shares_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Terjadwal"),
                    ("published", "Dipublikasi"),
                    ("archived", "Diarsipkan"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="news/gallery/")),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="news/thumbnails/"),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("alt_text", models.CharField(blank=True, max_length=100)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="news.news",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gambar Berita",
                "verbose_name_plural": "Gambar Berita",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("email", "Email"),
                            ("copy_link", "Copy Link"),
                            ("other", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="news.news",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Berita",
                "verbose_name_plural": "Share Berita",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="news.news",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Like Berita",
                "verbose_name_plural": "Like Berita",
                "ordering": ["-created_at"],
                "unique_together": {("news", "ip_address", "session_key")},
            },
        ),
    ]
