# Generated by Django 5.1.8 on 2025-08-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_comments_count_news_reading_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="featured_image_alt",
            field=models.CharField(
                blank=True, help_text="Alt text untuk gambar utama", max_length=200
            ),
        ),
    ]
