# Generated by Django 5.1.8 on 2025-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_featured_image_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="newscategory",
            name="order",
            field=models.PositiveIntegerField(default=0, help_text="Urutan kategori"),
        ),
    ]
