# Generated by Django 5.1.8 on 2025-08-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_newscategory_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="video_file",
            field=models.FileField(
                blank=True, help_text="File video lokal", upload_to="news/videos/"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="youtube_url",
            field=models.URLField(
                blank=True, help_text="URL video YouTube untuk embed"
            ),
        ),
    ]
