# Generated by Django 5.1.8 on 2025-08-31 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_news_video_file_news_youtube_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="likes_count",
        ),
        migrations.RemoveField(
            model_name="news",
            name="shares_count",
        ),
        migrations.RemoveField(
            model_name="news",
            name="views_count",
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Judul")),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("content", models.TextField(verbose_name="Isi Pengumuman")),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="Ringkasan"
                    ),
                ),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("info", "Informasi"),
                            ("warning", "Peringatan"),
                            ("urgent", "Mendesak"),
                            ("schedule", "Jadwal"),
                            ("event", "Acara"),
                            ("service", "Layanan"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Jenis Pengumuman",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Dipublikasi"),
                            ("archived", "Diarsipkan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Rendah"),
                            ("normal", "Normal"),
                            ("high", "Tinggi"),
                            ("urgent", "Mendesak"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Prioritas",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Pin di Atas"),
                ),
                (
                    "is_popup",
                    models.BooleanField(
                        default=False, verbose_name="Tampilkan sebagai Popup"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Tanggal Mulai")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Berakhir"
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True,
                        help_text="Contoh: Semua Warga, Ibu-ibu PKK, Remaja, dll",
                        max_length=100,
                        verbose_name="Target Audiens",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Narahubung"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="No. Telepon"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Lokasi"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Penulis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengumuman",
                "verbose_name_plural": "Pengumuman",
                "ordering": ["-is_pinned", "-priority", "-start_date"],
            },
        ),
    ]
