# Generated by Django 5.1.8 on 2025-08-29 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_name",
                    models.CharField(
                        choices=[
                            ("core", "Core Module"),
                            ("references", "References Module"),
                            ("events", "Events Module"),
                            ("documents", "Documents Module"),
                            ("business", "Business Module"),
                            ("village_profile", "Village Profile Module"),
                            ("posyandu", "Posyandu Module"),
                            ("letters", "Letters Module"),
                            ("beneficiaries", "Beneficiaries Module"),
                            ("organization", "Organization Module"),
                            ("news", "News Module"),
                            ("tourism", "Tourism Module"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_visible_in_menu", models.BooleanField(default=True)),
                ("menu_order", models.IntegerField(default=0)),
                ("icon_class", models.CharField(default="fas fa-cog", max_length=50)),
                ("requires_permission", models.BooleanField(default=False)),
                (
                    "required_permission",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("api_enabled", models.BooleanField(default=True)),
                ("api_rate_limit", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Module Settings",
                "verbose_name_plural": "Module Settings",
                "ordering": ["menu_order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Website Desa Pulosarok", max_length=200),
                ),
                (
                    "site_description",
                    models.TextField(default="Sistem Informasi Desa Pulosarok"),
                ),
                (
                    "site_logo",
                    models.ImageField(blank=True, null=True, upload_to="website/"),
                ),
                (
                    "site_favicon",
                    models.ImageField(blank=True, null=True, upload_to="website/"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("contact_address", models.TextField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light Theme"),
                            ("dark", "Dark Theme"),
                            ("auto", "Auto (System)"),
                        ],
                        default="light",
                        max_length=10,
                    ),
                ),
                ("primary_color", models.CharField(default="#3B82F6", max_length=7)),
                ("secondary_color", models.CharField(default="#10B981", max_length=7)),
                (
                    "default_language",
                    models.CharField(
                        choices=[
                            ("id", "Bahasa Indonesia"),
                            ("en", "English"),
                            ("jv", "Bahasa Jawa"),
                        ],
                        default="id",
                        max_length=5,
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Jakarta", max_length=50)),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                (
                    "google_analytics_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True, null=True)),
                ("allow_registration", models.BooleanField(default=False)),
                ("max_file_upload_size", models.IntegerField(default=10)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("whatsapp_notifications", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Website Settings",
                "verbose_name_plural": "Website Settings",
            },
        ),
        migrations.CreateModel(
            name="APIEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url_pattern", models.CharField(max_length=200)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_auth", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_endpoints",
                        to="core.modulesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Endpoint",
                "verbose_name_plural": "API Endpoints",
                "unique_together": {("module", "url_pattern", "method")},
            },
        ),
    ]
