# Generated by Django 5.2.4 on 2025-08-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "aid_type",
                    models.CharField(
                        choices=[
                            ("uang", "Bantuan Uang"),
                            ("sembako", "Sembako"),
                            ("kesehatan", "Bantuan Kesehatan"),
                            ("pendidikan", "Bantuan Pendidikan"),
                            ("perumahan", "Bantuan Perumahan"),
                            ("usaha", "Bantuan Usaha"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pusat", "Pemerintah Pusat"),
                            ("provinsi", "Pemerintah Provinsi"),
                            ("kabupaten", "Pemerintah Kabupaten"),
                            ("desa", "Pemerintah Desa"),
                            ("swasta", "Swasta"),
                            ("lsm", "LSM"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "value_per_beneficiary",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_budget", models.DecimalField(decimal_places=2, max_digits=15)),
                ("target_beneficiaries", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("requirements", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bantuan",
                "verbose_name_plural": "Bantuan",
            },
        ),
        migrations.CreateModel(
            name="AidDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distribution_date", models.DateField(blank=True, null=True)),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("approved", "Disetujui"),
                            ("distributed", "Sudah Disalurkan"),
                            ("rejected", "Ditolak"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("receipt_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Distribusi Bantuan",
                "verbose_name_plural": "Distribusi Bantuan",
            },
        ),
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("tidak_aktif", "Tidak Aktif"),
                            ("lulus", "Lulus"),
                            ("meninggal", "Meninggal"),
                            ("pindah", "Pindah"),
                        ],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                (
                    "economic_status",
                    models.CharField(
                        choices=[
                            ("miskin", "Miskin"),
                            ("sangat_miskin", "Sangat Miskin"),
                            ("rentan_miskin", "Rentan Miskin"),
                            ("tidak_miskin", "Tidak Miskin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("family_members_count", models.PositiveIntegerField(default=1)),
                ("house_condition", models.TextField(blank=True)),
                ("special_needs", models.TextField(blank=True)),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Penerima Bantuan",
                "verbose_name_plural": "Penerima Bantuan",
            },
        ),
        migrations.CreateModel(
            name="BeneficiaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("criteria", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategori Penerima Bantuan",
                "verbose_name_plural": "Kategori Penerima Bantuan",
            },
        ),
        migrations.CreateModel(
            name="BeneficiaryVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verification_date", models.DateField()),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Verifikasi"),
                            ("verified", "Terverifikasi"),
                            ("rejected", "Ditolak"),
                            ("need_update", "Perlu Update Data"),
                        ],
                        max_length=20,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True)),
                ("documents_checked", models.TextField(blank=True)),
                ("field_visit_conducted", models.BooleanField(default=False)),
                ("field_visit_notes", models.TextField(blank=True)),
                ("next_verification_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Verifikasi Penerima Bantuan",
                "verbose_name_plural": "Verifikasi Penerima Bantuan",
                "ordering": ["-verification_date"],
            },
        ),
    ]
