# Generated by Django 5.2.4 on 2025-08-26 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaries", "0001_initial"),
        ("references", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aid",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiddistribution",
            name="aid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to="beneficiaries.aid",
            ),
        ),
        migrations.AddField(
            model_name="aiddistribution",
            name="distributed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beneficiary_records",
                to="references.penduduk",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="registered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiddistribution",
            name="beneficiary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aid_received",
                to="beneficiaries.beneficiary",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="beneficiaries.beneficiarycategory",
            ),
        ),
        migrations.AddField(
            model_name="beneficiaryverification",
            name="beneficiary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifications",
                to="beneficiaries.beneficiary",
            ),
        ),
        migrations.AddField(
            model_name="beneficiaryverification",
            name="verifier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aiddistribution",
            unique_together={("aid", "beneficiary")},
        ),
        migrations.AlterUniqueTogether(
            name="beneficiary",
            unique_together={("person", "category")},
        ),
    ]
