# Generated by Django 5.2.4 on 2025-08-26 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("references", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PosyanduLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("capacity", models.PositiveIntegerField(default=50)),
                ("facilities", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("established_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coordinator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinated_posyandu",
                        to="references.penduduk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lokasi Posyandu",
                "verbose_name_plural": "Lokasi Posyandu",
            },
        ),
        migrations.CreateModel(
            name="NutritionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measurement_date", models.DateField()),
                ("age_months", models.PositiveIntegerField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "head_circumference",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "arm_circumference",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "nutrition_status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("kurang", "Kurang Gizi"),
                            ("buruk", "Gizi Buruk"),
                            ("lebih", "Gizi Lebih"),
                            ("stunting", "Stunting"),
                            ("wasting", "Wasting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vitamin_a_given", models.BooleanField(default=False)),
                ("iron_supplement_given", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_data",
                        to="references.penduduk",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posyandu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posyandu.posyandulocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Nutrisi",
                "verbose_name_plural": "Data Nutrisi",
                "ordering": ["-measurement_date"],
            },
        ),
        migrations.CreateModel(
            name="Immunization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vaccine_type",
                    models.CharField(
                        choices=[
                            ("bcg", "BCG"),
                            ("hepatitis_b", "Hepatitis B"),
                            ("polio", "Polio"),
                            ("dpt", "DPT"),
                            ("campak", "Campak"),
                            ("mmr", "MMR"),
                            ("covid19", "COVID-19"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vaccine_name", models.CharField(max_length=100)),
                ("dose_number", models.PositiveIntegerField(default=1)),
                ("immunization_date", models.DateField()),
                ("batch_number", models.CharField(blank=True, max_length=50)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("side_effects", models.TextField(blank=True)),
                ("next_dose_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immunizations",
                        to="references.penduduk",
                    ),
                ),
                (
                    "posyandu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posyandu.posyandulocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imunisasi",
                "verbose_name_plural": "Imunisasi",
                "ordering": ["-immunization_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_type",
                    models.CharField(
                        choices=[
                            ("balita", "Balita"),
                            ("ibu_hamil", "Ibu Hamil"),
                            ("ibu_menyusui", "Ibu Menyusui"),
                            ("lansia", "Lansia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("visit_date", models.DateField()),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("blood_pressure", models.CharField(blank=True, max_length=20)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("complaints", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("treatment", models.TextField(blank=True)),
                ("next_visit", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="references.penduduk",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posyandu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posyandu.posyandulocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rekam Kesehatan",
                "verbose_name_plural": "Rekam Kesehatan",
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="PosyanduSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("pemeriksaan", "Pemeriksaan Rutin"),
                            ("imunisasi", "Imunisasi"),
                            ("penyuluhan", "Penyuluhan"),
                            ("penimbangan", "Penimbangan"),
                            ("vitamin", "Pemberian Vitamin"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("schedule_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("target_participants", models.PositiveIntegerField(default=0)),
                ("actual_participants", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="posyandu.posyandulocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jadwal Posyandu",
                "verbose_name_plural": "Jadwal Posyandu",
                "ordering": ["-schedule_date", "start_time"],
            },
        ),
    ]
