# Generated by Django 5.2.4 on 2025-08-27 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posyandu", "0001_initial"),
        ("references", "0002_alter_penduduk_religion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="posyanduschedule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posyandu_location_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="IbuHamil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tanggal_hpht",
                    models.DateField(help_text="Hari Pertama Haid Terakhir"),
                ),
                (
                    "usia_kehamilan",
                    models.PositiveIntegerField(help_text="Dalam minggu"),
                ),
                ("tanggal_perkiraan_lahir", models.DateField()),
                (
                    "riwayat_kehamilan",
                    models.CharField(
                        choices=[
                            ("1", "Kehamilan Pertama"),
                            ("2", "Kehamilan Kedua"),
                            ("3", "Kehamilan Ketiga"),
                            ("4+", "Kehamilan Keempat atau Lebih"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "berat_badan_sebelum_hamil",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tinggi_badan",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("golongan_darah", models.CharField(blank=True, max_length=5)),
                ("riwayat_penyakit", models.TextField(blank=True)),
                (
                    "risiko_kehamilan",
                    models.CharField(
                        choices=[
                            ("rendah", "Risiko Rendah"),
                            ("tinggi", "Risiko Tinggi"),
                        ],
                        default="rendah",
                        max_length=10,
                    ),
                ),
                ("nomor_buku_kia", models.CharField(blank=True, max_length=50)),
                ("status_aktif", models.BooleanField(default=True)),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "penduduk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kehamilan",
                        to="references.penduduk",
                    ),
                ),
                (
                    "posyandu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posyandu.posyandulocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ibu Hamil",
                "verbose_name_plural": "Ibu Hamil",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PemeriksaanIbuHamil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_periksa", models.DateField()),
                (
                    "usia_kehamilan",
                    models.PositiveIntegerField(help_text="Dalam minggu"),
                ),
                ("berat_badan", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tekanan_darah", models.CharField(max_length=20)),
                (
                    "tinggi_fundus",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "lingkar_lengan_atas",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "hemoglobin",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("protein_urin", models.CharField(blank=True, max_length=10)),
                ("tablet_fe", models.BooleanField(default=False)),
                ("imunisasi_tt", models.BooleanField(default=False)),
                ("keluhan", models.TextField(blank=True)),
                ("anjuran", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ibu_hamil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pemeriksaan",
                        to="posyandu.ibuhamil",
                    ),
                ),
                (
                    "pemeriksa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pemeriksaan Ibu Hamil",
                "verbose_name_plural": "Pemeriksaan Ibu Hamil",
                "ordering": ["-tanggal_periksa"],
            },
        ),
        migrations.CreateModel(
            name="StuntingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_ukur", models.DateField()),
                ("usia_bulan", models.PositiveIntegerField()),
                ("tinggi_badan", models.DecimalField(decimal_places=2, max_digits=5)),
                ("berat_badan", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "z_score_tb_u",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Z-Score Tinggi Badan menurut Umur",
                        max_digits=5,
                    ),
                ),
                (
                    "z_score_bb_u",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Z-Score Berat Badan menurut Umur",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "z_score_bb_tb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Z-Score Berat Badan menurut Tinggi Badan",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status_stunting",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("pendek", "Pendek (Stunted)"),
                            ("sangat_pendek", "Sangat Pendek (Severely Stunted)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("asi_eksklusif", models.BooleanField(default=False)),
                (
                    "riwayat_bblr",
                    models.BooleanField(
                        default=False, help_text="Berat Badan Lahir Rendah"
                    ),
                ),
                ("riwayat_penyakit", models.TextField(blank=True)),
                (
                    "intervensi_diberikan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gizi", "Intervensi Gizi"),
                            ("kesehatan", "Intervensi Kesehatan"),
                            ("sanitasi", "Intervensi Sanitasi"),
                            ("edukasi", "Edukasi Keluarga"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hasil_intervensi", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stunting_data",
                        to="references.penduduk",
                    ),
                ),
                (
                    "posyandu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posyandu.posyandulocation",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Stunting",
                "verbose_name_plural": "Data Stunting",
                "ordering": ["-tanggal_ukur"],
            },
        ),
        migrations.CreateModel(
            name="PosyanduKader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jabatan",
                    models.CharField(
                        choices=[
                            ("ketua", "Ketua"),
                            ("wakil_ketua", "Wakil Ketua"),
                            ("sekretaris", "Sekretaris"),
                            ("bendahara", "Bendahara"),
                            ("anggota", "Anggota"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nomor_hp", models.CharField(blank=True, max_length=15)),
                ("tanggal_mulai", models.DateField()),
                ("tanggal_selesai", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("nonaktif", "Non-Aktif"),
                            ("cuti", "Cuti"),
                        ],
                        default="aktif",
                        max_length=10,
                    ),
                ),
                (
                    "sertifikat",
                    models.FileField(
                        blank=True, null=True, upload_to="kader_sertifikat/"
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "penduduk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kader_posyandu",
                        to="references.penduduk",
                    ),
                ),
                (
                    "posyandu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kader",
                        to="posyandu.posyandulocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kader Posyandu",
                "verbose_name_plural": "Kader Posyandu",
                "ordering": ["-created_at"],
                "unique_together": {("penduduk", "posyandu", "jabatan")},
            },
        ),
    ]
