# Generated by Django 5.2.4 on 2025-08-26 10:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("references", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LetterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nama Jenis Surat"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kode Surat"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="letter_templates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["docx", "pdf"]
                            )
                        ],
                        verbose_name="File Template",
                    ),
                ),
                (
                    "required_documents",
                    models.TextField(
                        blank=True,
                        help_text="Dokumen yang diperlukan (pisahkan dengan koma)",
                        verbose_name="Dokumen yang Diperlukan",
                    ),
                ),
                (
                    "processing_time_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Waktu Proses (Hari)"
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Biaya"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jenis Surat",
                "verbose_name_plural": "Jenis Surat",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Nomor Surat",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Perihal")),
                ("content", models.TextField(verbose_name="Isi Surat")),
                ("purpose", models.TextField(verbose_name="Tujuan Penggunaan")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Diajukan"),
                            ("in_review", "Sedang Ditinjau"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("completed", "Selesai"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Rendah"),
                            ("normal", "Normal"),
                            ("high", "Tinggi"),
                            ("urgent", "Mendesak"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Prioritas",
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Pengajuan"
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Persetujuan"
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Selesai"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Alasan Penolakan"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Catatan")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.penduduk",
                        verbose_name="Pemohon",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Disetujui Oleh",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
                (
                    "letter_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letters.lettertype",
                        verbose_name="Jenis Surat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Surat",
                "verbose_name_plural": "Surat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LetterAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("supporting_document", "Dokumen Pendukung"),
                            ("identity_card", "Kartu Identitas"),
                            ("certificate", "Sertifikat"),
                            ("photo", "Foto"),
                            ("other", "Lainnya"),
                        ],
                        max_length=30,
                        verbose_name="Jenis Lampiran",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Lampiran"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "file",
                    models.FileField(
                        upload_to="letter_attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                ]
                            )
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ukuran File (bytes)"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Wajib"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diunggah Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lampiran Surat",
                "verbose_name_plural": "Lampiran Surat",
                "ordering": ["-is_required", "title"],
            },
        ),
        migrations.CreateModel(
            name="LetterRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("external", "Eksternal"),
                            ("government", "Instansi Pemerintah"),
                            ("private", "Swasta"),
                            ("individual", "Perorangan"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Penerima",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nama Penerima"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Jabatan"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Organisasi/Instansi"
                    ),
                ),
                ("address", models.TextField(verbose_name="Alamat")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telepon"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Penerima Utama"),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("hand_delivery", "Antar Langsung"),
                            ("post", "Pos"),
                            ("email", "Email"),
                            ("fax", "Fax"),
                        ],
                        default="hand_delivery",
                        max_length=20,
                        verbose_name="Metode Pengiriman",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Pengiriman"
                    ),
                ),
                (
                    "received_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Diterima"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penerima Surat",
                "verbose_name_plural": "Penerima Surat",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="LetterTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Dibuat"),
                            ("submitted", "Diajukan"),
                            ("reviewed", "Ditinjau"),
                            ("approved", "Disetujui"),
                            ("rejected", "Ditolak"),
                            ("completed", "Diselesaikan"),
                            ("cancelled", "Dibatalkan"),
                            ("sent", "Dikirim"),
                            ("received", "Diterima"),
                            ("returned", "Dikembalikan"),
                        ],
                        max_length=20,
                        verbose_name="Aksi",
                    ),
                ),
                ("description", models.TextField(verbose_name="Deskripsi")),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="Lokasi"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Catatan")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Alamat IP"
                    ),
                ),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_history",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dilakukan Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Surat",
                "verbose_name_plural": "Tracking Surat",
                "ordering": ["-performed_at"],
            },
        ),
    ]
