# Generated by Django 5.2.4 on 2025-08-26 21:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="letter",
            name="ai_generated_content",
            field=models.TextField(
                blank=True, verbose_name="Konten yang Dihasilkan AI"
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="ai_suggestions_applied",
            field=models.JSONField(
                default=list, verbose_name="Saran AI yang Diterapkan"
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="estimated_reading_time",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Estimasi Waktu Baca (detik)"
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="is_digitally_signed",
            field=models.BooleanField(
                default=False, verbose_name="Sudah Ditandatangani Digital"
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="language",
            field=models.CharField(default="id", max_length=10, verbose_name="Bahasa"),
        ),
        migrations.AddField(
            model_name="letter",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="letter_pdfs/", verbose_name="File PDF"
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="public_url",
            field=models.CharField(
                blank=True, max_length=100, unique=True, verbose_name="URL Publik"
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="letter_qrcodes/",
                verbose_name="QR Code untuk Verifikasi",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="requires_ai_validation",
            field=models.BooleanField(
                default=True, verbose_name="Memerlukan Validasi AI"
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="requires_digital_signature",
            field=models.BooleanField(
                default=False, verbose_name="Memerlukan Tanda Tangan Digital"
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="signature_hash",
            field=models.CharField(
                blank=True,
                max_length=256,
                verbose_name="Hash Dokumen untuk Tanda Tangan",
            ),
        ),
        migrations.AddField(
            model_name="letter",
            name="word_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Jumlah Kata"),
        ),
        migrations.CreateModel(
            name="APIKeySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nama Layanan"
                    ),
                ),
                ("api_key", models.TextField(verbose_name="API Key (Encrypted)")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "max_requests_per_day",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Maksimal Request per Hari"
                    ),
                ),
                (
                    "current_usage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Penggunaan Hari Ini"
                    ),
                ),
                (
                    "last_reset_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Tanggal Reset Terakhir"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengaturan API Key",
                "verbose_name_plural": "Pengaturan API Key",
                "ordering": ["service_name"],
            },
        ),
        migrations.CreateModel(
            name="LetterAIValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validation_id",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="ID Validasi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("processing", "Sedang Diproses"),
                            ("completed", "Selesai"),
                            ("failed", "Gagal"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status Validasi",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Skor Kepercayaan (0-1)"
                    ),
                ),
                (
                    "validation_result",
                    models.JSONField(default=dict, verbose_name="Hasil Validasi"),
                ),
                (
                    "suggestions",
                    models.JSONField(default=list, verbose_name="Saran Perbaikan"),
                ),
                (
                    "grammar_check",
                    models.JSONField(
                        default=dict, verbose_name="Pemeriksaan Tata Bahasa"
                    ),
                ),
                (
                    "content_analysis",
                    models.JSONField(default=dict, verbose_name="Analisis Konten"),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Waktu Proses (ms)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Pesan Error"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Waktu Validasi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "letter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_validation",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validasi AI Surat",
                "verbose_name_plural": "Validasi AI Surat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LetterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "village_name",
                    models.CharField(
                        default="Desa Pulosarok",
                        max_length=100,
                        verbose_name="Nama Desa",
                    ),
                ),
                (
                    "village_address",
                    models.TextField(
                        default="Kecamatan Pulosarok, Kabupaten Indramayu",
                        verbose_name="Alamat Desa",
                    ),
                ),
                (
                    "village_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telepon Desa"
                    ),
                ),
                (
                    "village_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Desa"
                    ),
                ),
                (
                    "village_website",
                    models.URLField(blank=True, verbose_name="Website Desa"),
                ),
                (
                    "village_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="village_settings/",
                        verbose_name="Logo Desa",
                    ),
                ),
                (
                    "head_of_village_name",
                    models.CharField(max_length=100, verbose_name="Nama Kepala Desa"),
                ),
                (
                    "head_of_village_nip",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="NIP Kepala Desa"
                    ),
                ),
                (
                    "head_of_village_signature_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("image", "Gambar"),
                            ("text", "Teks"),
                        ],
                        default="digital",
                        max_length=20,
                        verbose_name="Jenis Tanda Tangan",
                    ),
                ),
                (
                    "head_of_village_signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signatures/",
                        verbose_name="Gambar Tanda Tangan",
                    ),
                ),
                (
                    "head_of_village_signature_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Teks Tanda Tangan"
                    ),
                ),
                (
                    "secretary_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nama Sekretaris Desa"
                    ),
                ),
                (
                    "secretary_nip",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="NIP Sekretaris"
                    ),
                ),
                (
                    "secretary_signature_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("image", "Gambar"),
                            ("text", "Teks"),
                        ],
                        default="digital",
                        max_length=20,
                        verbose_name="Jenis Tanda Tangan Sekretaris",
                    ),
                ),
                (
                    "secretary_signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="signatures/",
                        verbose_name="Gambar Tanda Tangan Sekretaris",
                    ),
                ),
                (
                    "letter_number_format",
                    models.CharField(
                        default="{code}/{number:03d}/{month:02d}/{year}",
                        help_text="Gunakan {code}, {number}, {month}, {year} sebagai placeholder",
                        max_length=100,
                        verbose_name="Format Nomor Surat",
                    ),
                ),
                (
                    "current_year_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Counter Tahun Ini"
                    ),
                ),
                (
                    "reset_counter_yearly",
                    models.BooleanField(
                        default=True, verbose_name="Reset Counter Setiap Tahun"
                    ),
                ),
                (
                    "enable_ai_validation",
                    models.BooleanField(
                        default=True, verbose_name="Aktifkan Validasi AI"
                    ),
                ),
                (
                    "ai_validation_threshold",
                    models.FloatField(
                        default=0.8, verbose_name="Threshold Validasi AI (0-1)"
                    ),
                ),
                (
                    "enable_ai_suggestions",
                    models.BooleanField(default=True, verbose_name="Aktifkan Saran AI"),
                ),
                (
                    "enable_digital_signature",
                    models.BooleanField(
                        default=True, verbose_name="Aktifkan Tanda Tangan Digital"
                    ),
                ),
                (
                    "signature_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="Sertifikat Digital",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengaturan Surat",
                "verbose_name_plural": "Pengaturan Surat",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LetterTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nama Template"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("official", "Surat Resmi"),
                            ("certificate", "Surat Keterangan"),
                            ("recommendation", "Surat Rekomendasi"),
                            ("invitation", "Surat Undangan"),
                            ("notification", "Surat Pemberitahuan"),
                            ("custom", "Template Kustom"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Template",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "content_template",
                    models.TextField(
                        help_text="Gunakan {{variable}} untuk placeholder",
                        verbose_name="Template Konten",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object dengan daftar variabel yang tersedia",
                        verbose_name="Variabel Template",
                    ),
                ),
                (
                    "css_styles",
                    models.TextField(
                        blank=True,
                        help_text="CSS untuk styling template",
                        verbose_name="CSS Styles",
                    ),
                ),
                (
                    "header_template",
                    models.TextField(blank=True, verbose_name="Template Header"),
                ),
                (
                    "footer_template",
                    models.TextField(blank=True, verbose_name="Template Footer"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Template Default"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jumlah Penggunaan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Surat",
                "verbose_name_plural": "Template Surat",
                "ordering": ["-is_default", "-usage_count", "name"],
            },
        ),
        migrations.AddField(
            model_name="letter",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="letters.lettertemplate",
                verbose_name="Template Surat",
            ),
        ),
        migrations.CreateModel(
            name="LetterDigitalSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signature_hash",
                    models.CharField(max_length=256, verbose_name="Hash Tanda Tangan"),
                ),
                (
                    "signature_data",
                    models.TextField(verbose_name="Data Tanda Tangan (Encrypted)"),
                ),
                (
                    "certificate_info",
                    models.JSONField(default=dict, verbose_name="Informasi Sertifikat"),
                ),
                (
                    "signature_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Waktu Tanda Tangan"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Alamat IP")),
                ("user_agent", models.TextField(verbose_name="User Agent")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("signed", "Ditandatangani"),
                            ("verified", "Terverifikasi"),
                            ("invalid", "Tidak Valid"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Verifikasi"
                    ),
                ),
                ("is_valid", models.BooleanField(default=True, verbose_name="Valid")),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_signatures",
                        to="letters.letter",
                        verbose_name="Surat",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Penandatangan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tanda Tangan Digital",
                "verbose_name_plural": "Tanda Tangan Digital",
                "ordering": ["-signature_timestamp"],
                "unique_together": {("letter", "signer")},
            },
        ),
    ]
