# Generated by Django 5.2.4 on 2025-08-26 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategori Bisnis",
                "verbose_name_plural": "Kategori Bisnis",
            },
        ),
        migrations.CreateModel(
            name="BusinessOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownership_percentage",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
                ),
                ("role", models.CharField(default="Pemilik", max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pemilik Bisnis",
                "verbose_name_plural": "Pemilik Bisnis",
            },
        ),
        migrations.CreateModel(
            name="BusinessProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit", models.CharField(default="pcs", max_length=50)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("min_stock", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="business_products/"
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Produk Bisnis",
                "verbose_name_plural": "Produk Bisnis",
            },
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("umkm", "UMKM"),
                            ("koperasi", "Koperasi"),
                            ("bumg", "BUMG"),
                            ("toko", "Toko"),
                            ("warung", "Warung"),
                            ("jasa", "Jasa"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField()),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("established_date", models.DateField(blank=True, null=True)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("tidak_aktif", "Tidak Aktif"),
                            ("tutup", "Tutup"),
                        ],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                ("employee_count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.businesscategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bisnis",
                "verbose_name_plural": "Bisnis",
            },
        ),
        migrations.CreateModel(
            name="BusinessFinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "Pemasukan"),
                            ("expense", "Pengeluaran"),
                            ("investment", "Investasi"),
                            ("loan", "Pinjaman"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.TextField()),
                ("transaction_date", models.DateField()),
                ("category", models.CharField(blank=True, max_length=100)),
                ("receipt_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finances",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keuangan Bisnis",
                "verbose_name_plural": "Keuangan Bisnis",
                "ordering": ["-transaction_date"],
            },
        ),
    ]
