# Generated by Django 5.2.4 on 2025-08-26 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0001_initial"),
        ("references", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="businessfinance",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="businessowner",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to="business.business",
            ),
        ),
        migrations.AddField(
            model_name="businessowner",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="references.penduduk"
            ),
        ),
        migrations.AddField(
            model_name="businessproduct",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="business.business",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="businessowner",
            unique_together={("business", "owner")},
        ),
    ]
