# Generated by Django 5.2.4 on 2025-08-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_aset", models.CharField(max_length=200)),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("tanah", "Tanah"),
                            ("bangunan", "Bangunan"),
                            ("kendaraan", "Kendaraan"),
                            ("peralatan", "Peralatan"),
                            ("inventaris", "Inventaris"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("kode_aset", models.CharField(max_length=50, unique=True)),
                ("deskripsi", models.TextField()),
                ("lokasi", models.CharField(max_length=200)),
                (
                    "nilai_perolehan",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("tanggal_perolehan", models.DateField()),
                (
                    "kondisi",
                    models.CharField(
                        choices=[
                            ("baik", "Baik"),
                            ("rusak_ringan", "Rusak Ringan"),
                            ("rusak_berat", "Rusak Berat"),
                            ("hilang", "Hilang"),
                        ],
                        default="baik",
                        max_length=20,
                    ),
                ),
                ("masa_manfaat", models.PositiveIntegerField(help_text="Dalam tahun")),
                (
                    "penyusutan_per_tahun",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "nilai_buku",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("penanggung_jawab", models.CharField(max_length=100)),
                ("nomor_sertifikat", models.CharField(blank=True, max_length=100)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="aset_photos/"),
                ),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Aset",
                "verbose_name_plural": "Aset",
            },
        ),
        migrations.CreateModel(
            name="BUMG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("nomor_sk", models.CharField(max_length=100, unique=True)),
                ("tanggal_sk", models.DateField()),
                ("alamat", models.TextField()),
                ("direktur", models.CharField(max_length=100)),
                ("komisaris", models.CharField(max_length=100)),
                (
                    "modal_dasar",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "modal_disetor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("bidang_usaha", models.TextField()),
                ("telepon", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("tidak_aktif", "Tidak Aktif"),
                            ("pending", "Pending"),
                        ],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "BUMG",
                "verbose_name_plural": "BUMG",
            },
        ),
        migrations.CreateModel(
            name="Koperasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("nomor_badan_hukum", models.CharField(max_length=100, unique=True)),
                ("tanggal_berdiri", models.DateField()),
                ("alamat", models.TextField()),
                ("ketua", models.CharField(max_length=100)),
                ("sekretaris", models.CharField(max_length=100)),
                ("bendahara", models.CharField(max_length=100)),
                ("jumlah_anggota", models.PositiveIntegerField(default=0)),
                (
                    "modal_awal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "modal_sekarang",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("jenis_usaha", models.TextField()),
                ("telepon", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("tidak_aktif", "Tidak Aktif"),
                            ("pending", "Pending"),
                        ],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Koperasi",
                "verbose_name_plural": "Koperasi",
            },
        ),
        migrations.CreateModel(
            name="LayananJasa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("kesehatan", "Kesehatan"),
                            ("pendidikan", "Pendidikan"),
                            ("transportasi", "Transportasi"),
                            ("konstruksi", "Konstruksi"),
                            ("teknologi", "Teknologi"),
                            ("keuangan", "Keuangan"),
                            ("pertanian", "Pertanian"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("deskripsi", models.TextField()),
                ("penyedia", models.CharField(max_length=100)),
                ("telepon", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("alamat", models.TextField()),
                (
                    "pengalaman",
                    models.PositiveIntegerField(default=0, help_text="Dalam tahun"),
                ),
                (
                    "harga_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "harga_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "satuan_harga",
                    models.CharField(
                        choices=[
                            ("per_jam", "Per Jam"),
                            ("per_hari", "Per Hari"),
                            ("per_minggu", "Per Minggu"),
                            ("per_bulan", "Per Bulan"),
                            ("per_proyek", "Per Proyek"),
                            ("lainnya", "Lainnya"),
                        ],
                        default="per_proyek",
                        max_length=20,
                    ),
                ),
                ("waktu_layanan", models.CharField(blank=True, max_length=200)),
                ("area_layanan", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("tidak_aktif", "Tidak Aktif"),
                            ("pending", "Pending"),
                        ],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("sertifikat", models.CharField(blank=True, max_length=200)),
                ("keunggulan", models.TextField(blank=True)),
                ("syarat_ketentuan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Layanan Jasa",
                "verbose_name_plural": "Layanan Jasa",
            },
        ),
        migrations.CreateModel(
            name="UKM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_usaha", models.CharField(max_length=200)),
                ("pemilik", models.CharField(max_length=100)),
                ("nik_pemilik", models.CharField(max_length=16)),
                ("alamat_usaha", models.TextField()),
                ("alamat_pemilik", models.TextField()),
                ("jenis_usaha", models.CharField(max_length=100)),
                (
                    "skala_usaha",
                    models.CharField(
                        choices=[
                            ("mikro", "Mikro"),
                            ("kecil", "Kecil"),
                            ("menengah", "Menengah"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modal_awal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "omzet_bulanan",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("jumlah_karyawan", models.PositiveIntegerField(default=1)),
                ("tanggal_mulai", models.DateField()),
                ("nomor_izin", models.CharField(blank=True, max_length=100)),
                ("telepon", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("produk_utama", models.TextField()),
                ("target_pasar", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aktif", "Aktif"),
                            ("tidak_aktif", "Tidak Aktif"),
                            ("pending", "Pending"),
                        ],
                        default="aktif",
                        max_length=20,
                    ),
                ),
                ("keterangan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "UKM",
                "verbose_name_plural": "UKM",
            },
        ),
    ]
