# Generated by Django 5.2.4 on 2025-08-26 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_aset_bumg_koperasi_layananjasa_ukm"),
    ]

    operations = [
        migrations.CreateModel(
            name="JenisKoperasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100, unique=True)),
                ("deskripsi", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jenis Koperasi",
                "verbose_name_plural": "Jenis Koperasi",
                "ordering": ["nama"],
            },
        ),
        migrations.AddField(
            model_name="koperasi",
            name="jenis_koperasi",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="business.jeniskoperasi",
            ),
        ),
    ]
