# Generated by Django 5.2.4 on 2025-08-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VillageGeography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total area in hectares",
                        max_digits=10,
                    ),
                ),
                (
                    "agricultural_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "residential_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "forest_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "water_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "altitude_min",
                    models.IntegerField(
                        blank=True, help_text="Minimum altitude in meters", null=True
                    ),
                ),
                (
                    "altitude_max",
                    models.IntegerField(
                        blank=True, help_text="Maximum altitude in meters", null=True
                    ),
                ),
                (
                    "climate_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "rainfall_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average rainfall in mm/year",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "temperature_min",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "temperature_max",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "boundaries_north",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "boundaries_south",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "boundaries_east",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "boundaries_west",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Geografi Desa",
                "verbose_name_plural": "Geografi Desa",
            },
        ),
        migrations.CreateModel(
            name="VillageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "period_start",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("period_end", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "historical_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="village_history/"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sejarah Desa",
                "verbose_name_plural": "Sejarah Desa",
                "ordering": ["period_start"],
            },
        ),
        migrations.CreateModel(
            name="VillageMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "map_type",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIVE", "Peta Administrasi"),
                            ("TOPOGRAPHIC", "Peta Topografi"),
                            ("LAND_USE", "Peta Penggunaan Lahan"),
                            ("TOURISM", "Peta Wisata"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("map_image", models.ImageField(upload_to="village_maps/")),
                (
                    "map_file",
                    models.FileField(
                        blank=True,
                        help_text="PDF or other map files",
                        null=True,
                        upload_to="village_maps/files/",
                    ),
                ),
                (
                    "coordinates_center_lat",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "coordinates_center_lng",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("zoom_level", models.IntegerField(default=15)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Peta Desa",
                "verbose_name_plural": "Peta Desa",
            },
        ),
        migrations.CreateModel(
            name="VillageVision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("vision_text", models.TextField()),
                ("mission_text", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Visi Misi Desa",
                "verbose_name_plural": "Visi Misi Desa",
                "ordering": ["-effective_date"],
            },
        ),
    ]
