# Generated by Django 5.2.4 on 2025-08-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleMapsEmblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Emblem Desa Pulosarok", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Deskripsi tentang emblem desa", null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Latitude koordinat emblem di Google Maps",
                        max_digits=10,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Longitude koordinat emblem di Google Maps",
                        max_digits=11,
                    ),
                ),
                (
                    "zoom_level",
                    models.IntegerField(
                        default=15, help_text="Level zoom Google Maps (1-20)"
                    ),
                ),
                (
                    "emblem_size",
                    models.CharField(
                        choices=[
                            ("small", "Kecil"),
                            ("medium", "Sedang"),
                            ("large", "Besar"),
                        ],
                        default="medium",
                        help_text="Ukuran emblem di peta",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="Tampilkan emblem di peta"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Google Maps Emblem",
                "verbose_name_plural": "Google Maps Emblem",
                "ordering": ["-created_at"],
            },
        ),
    ]
