# Generated by Django 5.1.8 on 2025-08-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_profile", "0002_googlemapsemblem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="villagemap",
            name="map_image",
        ),
        migrations.AddField(
            model_name="villagemap",
            name="google_maps_embed",
            field=models.TextField(
                blank=True, help_text="Kode embed dari Google Maps (iframe)", null=True
            ),
        ),
        migrations.AddField(
            model_name="villagemap",
            name="google_maps_url",
            field=models.URLField(blank=True, help_text="Google Maps URL", null=True),
        ),
    ]
