# Generated by Django 5.1.8 on 2025-08-30 06:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_profile", "0003_remove_villagemap_map_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VillageHistoryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="village_history/photos/", verbose_name="Foto"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Keterangan"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Deskripsi"),
                ),
                (
                    "photographer",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Fotografer"
                    ),
                ),
                (
                    "photo_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Foto"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Lokasi"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Foto Unggulan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Urutan Tampil"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
            ],
            options={
                "verbose_name": "Foto Sejarah",
                "verbose_name_plural": "Foto Sejarah",
                "ordering": ["display_order", "-is_featured", "created_at"],
            },
        ),
        migrations.DeleteModel(
            name="GoogleMapsEmblem",
        ),
        migrations.DeleteModel(
            name="VillageGeography",
        ),
        migrations.DeleteModel(
            name="VillageMap",
        ),
        migrations.DeleteModel(
            name="VillageVision",
        ),
        migrations.AlterModelOptions(
            name="villagehistory",
            options={
                "ordering": ["-is_featured", "year_start", "period_start"],
                "verbose_name": "Sejarah Desa",
                "verbose_name_plural": "Sejarah Desa",
            },
        ),
        migrations.RemoveField(
            model_name="villagehistory",
            name="historical_image",
        ),
        migrations.AddField(
            model_name="villagehistory",
            name="author",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Penulis"
            ),
        ),
        migrations.AddField(
            model_name="villagehistory",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="village_history/featured/",
                verbose_name="Gambar Utama",
            ),
        ),
        migrations.AddField(
            model_name="villagehistory",
            name="featured_image_caption",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Keterangan Gambar Utama",
            ),
        ),
        migrations.AddField(
            model_name="villagehistory",
            name="history_type",
            field=models.CharField(
                choices=[
                    ("FOUNDING", "Sejarah Berdiri"),
                    ("DEVELOPMENT", "Perkembangan"),
                    ("CULTURE", "Budaya & Tradisi"),
                    ("ECONOMY", "Ekonomi"),
                    ("SOCIAL", "Sosial"),
                    ("GOVERNMENT", "Pemerintahan"),
                    ("OTHER", "Lainnya"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Jenis Sejarah",
            ),
        ),
        migrations.AddField(
            model_name="villagehistory",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=220, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="villagehistory",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Sumber informasi sejarah",
                max_length=200,
                null=True,
                verbose_name="Sumber",
            ),
        ),
        migrations.AddField(
            model_name="villagehistory",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Ringkasan singkat sejarah (maksimal 500 karakter)",
                max_length=500,
                null=True,
                verbose_name="Ringkasan",
            ),
        ),
        migrations.AddField(
            model_name="villagehistory",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Jumlah Dilihat"),
        ),
        migrations.AddField(
            model_name="villagehistory",
            name="year_end",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Tahun Berakhir",
            ),
        ),
        migrations.AddField(
            model_name="villagehistory",
            name="year_start",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Tahun Mulai",
            ),
        ),
        migrations.AlterField(
            model_name="villagehistory",
            name="content",
            field=models.TextField(verbose_name="Konten Lengkap"),
        ),
        migrations.AlterField(
            model_name="villagehistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
        ),
        migrations.AlterField(
            model_name="villagehistory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AlterField(
            model_name="villagehistory",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Unggulan"),
        ),
        migrations.AlterField(
            model_name="villagehistory",
            name="period_end",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Periode Berakhir"
            ),
        ),
        migrations.AlterField(
            model_name="villagehistory",
            name="period_start",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Periode Mulai"
            ),
        ),
        migrations.AlterField(
            model_name="villagehistory",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Judul"),
        ),
        migrations.AlterField(
            model_name="villagehistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
        ),
        migrations.AddIndex(
            model_name="villagehistory",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="village_pro_is_acti_50e2f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="villagehistory",
            index=models.Index(
                fields=["history_type"], name="village_pro_history_b9cd3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="villagehistory",
            index=models.Index(
                fields=["year_start"], name="village_pro_year_st_910a25_idx"
            ),
        ),
        migrations.AddField(
            model_name="villagehistoryphoto",
            name="history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="village_profile.villagehistory",
                verbose_name="Sejarah",
            ),
        ),
        migrations.AddIndex(
            model_name="villagehistoryphoto",
            index=models.Index(
                fields=["history", "is_active"], name="village_pro_history_b77d69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="villagehistoryphoto",
            index=models.Index(
                fields=["is_featured"], name="village_pro_is_feat_c8a683_idx"
            ),
        ),
    ]
