# Generated by Django 5.2.4 on 2025-08-26 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisabilitasType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jenis Disabilitas",
                "verbose_name_plural": "Jenis Disabilitas",
            },
        ),
        migrations.CreateModel(
            name="Dusun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "area_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Area in hectares",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("population_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dusun",
                "verbose_name_plural": "Dusun",
            },
        ),
        migrations.CreateModel(
            name="ReligionReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agama",
                "verbose_name_plural": "Agama",
            },
        ),
        migrations.CreateModel(
            name="Lorong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=15)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Length in meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("house_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dusun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lorongs",
                        to="references.dusun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lorong",
                "verbose_name_plural": "Lorong",
                "unique_together": {("dusun", "code")},
            },
        ),
        migrations.CreateModel(
            name="Penduduk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nik",
                    models.CharField(max_length=16, unique=True, verbose_name="NIK"),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")], max_length=1
                    ),
                ),
                ("birth_place", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("religion", models.CharField(max_length=50)),
                ("education", models.CharField(blank=True, max_length=50, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("BELUM_KAWIN", "Belum Kawin"),
                            ("KAWIN", "Kawin"),
                            ("CERAI_HIDUP", "Cerai Hidup"),
                            ("CERAI_MATI", "Cerai Mati"),
                        ],
                        max_length=15,
                    ),
                ),
                ("address", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dusun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residents",
                        to="references.dusun",
                    ),
                ),
                (
                    "lorong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="residents",
                        to="references.lorong",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penduduk",
                "verbose_name_plural": "Penduduk",
            },
        ),
        migrations.CreateModel(
            name="DisabilitasData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("RINGAN", "Ringan"),
                            ("SEDANG", "Sedang"),
                            ("BERAT", "Berat"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("diagnosis_date", models.DateField(blank=True, null=True)),
                ("needs_assistance", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "disability_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.disabilitastype",
                    ),
                ),
                (
                    "penduduk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disabilities",
                        to="references.penduduk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Disabilitas",
                "verbose_name_plural": "Data Disabilitas",
                "unique_together": {("penduduk", "disability_type")},
            },
        ),
    ]
