# Generated by Django 5.2.4 on 2025-08-27 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0002_alter_penduduk_religion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="penduduk",
            options={
                "ordering": ["name"],
                "verbose_name": "Penduduk",
                "verbose_name_plural": "Penduduk",
            },
        ),
        migrations.AddField(
            model_name="penduduk",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("AB", "AB"), ("O", "O")],
                max_length=2,
                null=True,
                verbose_name="Golongan Darah",
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="citizenship",
            field=models.CharField(
                choices=[("WNI", "WNI"), ("WNA", "WNA")],
                default="WNI",
                max_length=3,
                verbose_name="Kewarganegaraan",
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_penduduk",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dibuat Oleh",
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="death_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tanggal Meninggal"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="death_place",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tempat Meninggal"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="emergency_contact",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Kontak Darurat"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="emergency_phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Telepon Darurat"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="emergency_relationship",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Hubungan dengan Kontak Darurat",
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="family_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="family_members",
                to="references.penduduk",
                verbose_name="Kepala Keluarga",
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="height",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tinggi badan dalam cm",
                null=True,
                verbose_name="Tinggi Badan",
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Nomor Rumah"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="is_alive",
            field=models.BooleanField(default=True, verbose_name="Masih Hidup"),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="kk_number",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="Nomor Kartu Keluarga",
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="mobile_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Nomor HP"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="passport_expiry",
            field=models.DateField(
                blank=True, null=True, verbose_name="Berlaku Hingga"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="passport_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Nomor Paspor"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Nomor Telepon"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Kode Pos"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="relationship_to_head",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Hubungan dengan Kepala Keluarga",
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="rt_number",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Nomor RT"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="rw_number",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Nomor RW"
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_penduduk",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Diperbarui Oleh",
            ),
        ),
        migrations.AddField(
            model_name="penduduk",
            name="weight",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Berat badan dalam kg",
                null=True,
                verbose_name="Berat Badan",
            ),
        ),
        migrations.AlterField(
            model_name="penduduk",
            name="address",
            field=models.TextField(verbose_name="Alamat Lengkap"),
        ),
        migrations.AlterField(
            model_name="penduduk",
            name="birth_date",
            field=models.DateField(verbose_name="Tanggal Lahir"),
        ),
        migrations.AlterField(
            model_name="penduduk",
            name="birth_place",
            field=models.CharField(max_length=100, verbose_name="Tempat Lahir"),
        ),
        migrations.AlterField(
            model_name="penduduk",
            name="dusun",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="residents",
                to="references.dusun",
                verbose_name="Dusun",
            ),
        ),
        migrations.AlterField(
            model_name="penduduk",
            name="education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TIDAK_BELUM_SEKOLAH", "Tidak/Belum Sekolah"),
                    ("BELUM_TAMAT_SD", "Belum Tamat SD/Sederajat"),
                    ("TAMAT_SD", "Tamat SD/Sederajat"),
                    ("SLTP", "SLTP/Sederajat"),
                    ("SLTA", "SLTA/Sederajat"),
                    ("D1", "D1"),
                    ("D2", "D2"),
                    ("D3", "D3"),
                    ("D4_S1", "D4/S1"),
                    ("S2", "S2"),
                    ("S3", "S3"),
                ],
                max_length=50,
                null=True,
                verbose_name="Pendidikan",
            ),
        ),
        migrations.AlterField(
            model_name="penduduk",
            name="gender",
            field=models.CharField(
                choices=[("L", "Laki-laki"), ("P", "Perempuan")],
                max_length=1,
                verbose_name="Jenis Kelamin",
            ),
        ),
        migrations.AlterField(
            model_name="penduduk",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AlterField(
            model_name="penduduk",
            name="lorong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="residents",
                to="references.lorong",
                verbose_name="Lorong",
            ),
        ),
        migrations.AlterField(
            model_name="penduduk",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("BELUM_KAWIN", "Belum Kawin"),
                    ("KAWIN", "Kawin"),
                    ("CERAI_HIDUP", "Cerai Hidup"),
                    ("CERAI_MATI", "Cerai Mati"),
                ],
                max_length=15,
                verbose_name="Status Perkawinan",
            ),
        ),
        migrations.AlterField(
            model_name="penduduk",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nama Lengkap"),
        ),
        migrations.AlterField(
            model_name="penduduk",
            name="occupation",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Pekerjaan"
            ),
        ),
        migrations.AlterField(
            model_name="penduduk",
            name="religion",
            field=models.CharField(
                choices=[
                    ("Islam", "Islam"),
                    ("Kristen Protestan", "Kristen Protestan"),
                    ("Kristen Katolik", "Kristen Katolik"),
                    ("Hindu", "Hindu"),
                    ("Buddha", "Buddha"),
                    ("Konghucu", "Konghucu"),
                    ("Kepercayaan", "Kepercayaan"),
                ],
                max_length=50,
                verbose_name="Agama",
            ),
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kk_number",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Nomor Kartu Keluarga"
                    ),
                ),
                (
                    "family_status",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Keluarga Normal"),
                            ("MISKIN", "Keluarga Miskin"),
                            ("PRASEJAHTERA", "Keluarga Prasejahtera"),
                            ("SEJAHTERA", "Keluarga Sejahtera"),
                            ("SEJAHTERA_1", "Keluarga Sejahtera 1"),
                            ("SEJAHTERA_2", "Keluarga Sejahtera 2"),
                            ("SEJAHTERA_3", "Keluarga Sejahtera 3"),
                            ("SEJAHTERA_3_PLUS", "Keluarga Sejahtera 3+"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="Status Keluarga",
                    ),
                ),
                (
                    "total_members",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Jumlah Anggota"
                    ),
                ),
                (
                    "total_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total pendapatan keluarga per bulan",
                        max_digits=15,
                        null=True,
                        verbose_name="Total Pendapatan",
                    ),
                ),
                ("address", models.TextField(verbose_name="Alamat Keluarga")),
                (
                    "rt_number",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Nomor RT"
                    ),
                ),
                (
                    "rw_number",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Nomor RW"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Nomor Rumah"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Kode Pos"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Nomor Telepon",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dusun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.dusun",
                        verbose_name="Dusun",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headed_families",
                        to="references.penduduk",
                        verbose_name="Kepala Keluarga",
                    ),
                ),
                (
                    "lorong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.lorong",
                        verbose_name="Lorong",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keluarga",
                "verbose_name_plural": "Keluarga",
            },
        ),
    ]
